# Generated by Django 5.2.1 on 2025-05-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atriskcandidates",
            options={
                "verbose_name": "Xavf ostidagi nomzodlar so'rovi",
                "verbose_name_plural": "Xavf ostidagi nomzodlar so'rovlari",
            },
        ),
        migrations.AlterModelOptions(
            name="excellentcandidates",
            options={
                "verbose_name": "A'lochi nomzodlar so'rovi",
                "verbose_name_plural": "A'lochi nomzodlar so'rovlari",
            },
        ),
        migrations.AlterField(
            model_name="atriskcandidates",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="atriskcandidates",
            name="selected_groupmates",
            field=models.ManyToManyField(
                related_name="atrisk_candidates",
                to="students.student",
                verbose_name="Xavf ostida deb belgilangan guruhdoshlar",
            ),
        ),
        migrations.AlterField(
            model_name="atriskcandidates",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atrisk_nominator",
                to="students.student",
                verbose_name="So'rov yuborgan talaba",
            ),
        ),
        migrations.AlterField(
            model_name="excellentcandidates",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="excellentcandidates",
            name="selected_groupmates",
            field=models.ManyToManyField(
                related_name="excellent_candidates",
                to="students.student",
                verbose_name="A'lochi deb belgilangan guruhdoshlar",
            ),
        ),
        migrations.AlterField(
            model_name="excellentcandidates",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excellent_nominator",
                to="students.student",
                verbose_name="So'rov yuborgan talaba",
            ),
        ),
    ]
