# Generated by Django 5.2.1 on 2025-05-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_atriskcandidates_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atriskreason",
            options={
                "verbose_name": "Xavf uchun sabab",
                "verbose_name_plural": "Xavf uchun sabablar",
            },
        ),
        migrations.AlterModelOptions(
            name="excellencereason",
            options={
                "verbose_name": "A'lochi uchun sabab",
                "verbose_name_plural": "A'lochi uchun sabablar",
            },
        ),
        migrations.AlterField(
            model_name="atriskreason",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reasons",
                to="students.atriskcandidates",
                verbose_name="Xavf ostidagi nomzodlar so'rovi",
            ),
        ),
        migrations.AlterField(
            model_name="atriskreason",
            name="reason",
            field=models.CharField(
                choices=[
                    (
                        "difficulty",
                        "Dars materialini tushunishda qiyinchilikka duch keladi",
                    ),
                    ("unprepared", "Imtihonlarga yaxshi tayyorlanmaydi"),
                    ("poor_time", "Vaqtini samarali boshqara olmaydi"),
                    ("motivation", "Motivatsiya yetishmaydi"),
                    ("confidence", "O‘ziga bo‘lgan ishonch yetarli emas"),
                    (
                        "teacher_relation",
                        "O‘qituvchining talabaga bo‘lgan shaxsiy munosabati ta’sir qiladi",
                    ),
                    (
                        "subjective_factors",
                        "Tanish-bilishchilik yoki boshqa subyektiv omillar ta’sir qiladi",
                    ),
                ],
                max_length=30,
                verbose_name="Sabab",
            ),
        ),
        migrations.AlterField(
            model_name="excellencereason",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reasons",
                to="students.excellentcandidates",
                verbose_name="A'lochi nomzodlar so'rovi",
            ),
        ),
        migrations.AlterField(
            model_name="excellencereason",
            name="reason",
            field=models.CharField(
                choices=[
                    ("responsibility", "Javobgarlik hissi kuchli"),
                    ("hardwork", "Tinimsiz mehnat qiladi"),
                    ("attentive", "Darslarni diqqat bilan tinglaydi"),
                    ("efficient_time", "Vaqtidan samarali foydalanadi"),
                    ("extra_sources", "Qo‘shimcha manbalardan bilim oladi"),
                    ("good_relation", "O‘qituvchilar bilan yaxshi munosabatga ega"),
                    ("active_events", "Tadbirlarda faol qatnashadi"),
                ],
                max_length=30,
                verbose_name="Sabab",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(max_length=50, verbose_name="Kurs"),
        ),
        migrations.AlterField(
            model_name="student",
            name="direction",
            field=models.CharField(max_length=100, verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name="student",
            name="faculty",
            field=models.CharField(max_length=100, verbose_name="Fakultet"),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="F.I.Sh."),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.CharField(max_length=50, verbose_name="Guruh"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Talaba ID"
            ),
        ),
    ]
