# Generated by Django 5.2.1 on 2025-05-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_atriskreason_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram ID"
            ),
        ),
    ]
