# Generated by Django 5.2.1 on 2025-05-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_participation', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'telegram_id'), name='uniq_student_telegram')],
            },
        ),
    ]
