# Generated by Django 5.2.1 on 2025-05-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_surveyparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyparticipation',
            name='finished_at',
        ),
    ]
