services:
  web:
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # 🔥 static fayllar saqlanadigan joy
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
  bot:
    build: .
    command: python bot/bot.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - app-network
    

volumes:
  static_volume:  # 🔥 volume e’lon qilinadi
networks:
  app-network:
    driver: bridge
